---
title: "L01 Review"
subtitle: "Data Science 3 with R (STAT 301-3)"
output: 
  html_document:
    toc: true
    toc_float: true
    highlight: "tango"
---

## Overview

The goal of this lab is to review vocabulary and concepts from the Data Science 2 with R (STAT 301-2).

## Questions

When completing the following questions ensure that that your solutions are clearly indicated and that your document is neatly formatted. Consider including diagrams that in some of your answers since it might make things easier to describe. 


### Question 1

Provide a brief outline/overview of the steps involved in a supervised machine learning process. Could provide this as a bulleted list. 

Answer:

- Gathering data
- Prepping data
- Choosing model
- Training
- Evaluating 
- Tuning
- Predicting 

<br>

### Question 2

Explain the difference between supervised and unsupervised learning.

Answer: 

Supervised learning is machine learning that uses trained models using labeled data. Models need to map the input variable with the output variable. Further, the model training must be supervised. Supervised learning can be used for classification and regression problems. Unsupervised learning is machine learning that uses patterns inferred from unlabeled input data. Labeled data is not needed for unsupervised learning because the machine finds patterns on its own. Unsupervised learning is used for clustering and association problems.

<br>

### Question 3 

In general, we can classify a model by its purpose into 1 of the 3 categories below. Provide a brief description of the goals of these model classes.

1. Descriptive Models: Summarizes characteristics of a dataset

2. Inferential Models: Test hypothesis or assess whether data is generalizable based on data

3. Predictive Models: Produce predictions about future data points given a past dataset

<br>

### Question 4 

We can further describe/classify predictive models by how they were derived or developed as being either mechanistic or empirically driven. 

#### Part A
What does it mean to be a mechanistic model?

Answer:

A mechanistic model uses a theory to predict what will happen in the real world. Mechanistic models use mathematical expressions that best describe the physical or biological process.

#### Part B
What does it mean to be an empirically driven model?

Answer:

Empirical models use real-world events to develop a theory. The idea is that if you observe some particular outcome following some particular circumstance then you can reliably predict that outcome in the future.

#### Part C
How does the mechanistic and empirically driven model terminology relate to the parametric and nonparametric model terminology? 

Answer:

Parametric Methods uses a fixed number of parameters to build the model. Non-Parametric Methods use the flexible number of parameters to build the model. It would seem that mechanistic models are parametric methods and empirical models are nonparametric methods. 

#### Part D
In general, is a mechanistic or empirically driven model easier to understand? Explain.

Answer:

Mechanistic models are easier to understand because they are based on mathematical expressions, so there are clearer results. They are also based on concrete assumptions drawn from previous data points. 

#### Part E
How does mechanistic and empirically driven model terminology relate to the idea of model flexibility? That is, which would be more or less flexible than the other.

Answer:

Empirically driven models are more flexible than mechanistic models because they are based on more vague assumptions rather than concrete data points and mathematical expressions. 

#### Part F
Describe the bias-variance trade-off when considering the use of a mechanistic or empirically driven model. 

Answer:

The bias-variance trade-off is about finding the right balance between the two because the increase of one will result in the decrease of the other and vice versa. Empirically driven models are better for understanding this trade-off.

<br>

### Question 5 

Explain the difference between a regression and classification machine learning (ML) problems.

Answer:

Regression machine learning problems predict numeric outcomes, while classification machine learning problems are used to predict discrete values. A regression problem would ask for things like salary or age, while a classification problem would ask for things like Yes/No or True/False.

<br>

### Question 6 

When splitting the data, why is it useful to stratify by the outcome/target variable? 

Answer:

Stratified sampling splits a dataset such that each split is similar with respect to a particular variable. Stratifying data also ensures that the sample and treatment groups are representative of the broader dataset.  

<br>

### Question 7 

Briefly describe how v-fold cross validation with repeats is used to estimate test RMSE. Also provide an explanation of why we use it. 

Answer:

V-fold cross-validation is repeating the cross-validation procedure multipletimes and reporting the mean result across all folds from all runs. Performing more folds and resamples increases the accuracy of the overall resampling estimate. Although there are diminishing returns after hitting a certain point, using more resamples helps the accuracy. Cross-validation also gives models the chance to train on multiple train-test splits, which gives a better indication of how well the model will perform on unseen data. RMSE is root mean squared error determines the standard error of the mean. RMSE is lowered, ie error is lowered, when you cross-validate the data.

<br>

### Question 8

When might we use a bootstrap resampling procedure instead of v-fold cross validation to estimate test RMSE?

Answer:

We use bootstrapping resampling procedures instead of v-fold cross validation to estimate test RMSE when we are approximating the sampling distribution of statistics whose theoretical properties are intractable. A bootstrap sample of the training set is a sample that is the same size as the training set but is drawn with replacement. This means that some training set data points are selected multiple times for the analysis set. Bootstrap samples produce performance estimates that have very low variance (unlike cross-validation) but have significant pessimistic bias. 

<br>

### Question 9 

Briefly describe model tuning and why we use it.

Answer:

Tuning is the process of maximizing a model's performance by selecting appropriate “hyperparameters.” Model tuning allows us to customize our models so they generate the most accurate outcomes and give us highly valuable insights into our data.

<br>

### Question 10 

What are two common performance metrics when dealing with a regression ML problem?

Answer:

RMSE and MAe

What are two common performance metrics when dealing with a classification ML problem?

Answer:

Confusion Matrix and AUC-ROC curve

<br>

### Question 11

A political candidate's campaign has detailed voter history data for their constituents. The campaign is interested in two questions:

1. Given a voter's profile/data how likely is it that they will vote in favor of the candidate?

Answer:

Predictive because we use a voter's profile and predict a numeric outcome given a dataset of other instances with other voters. We use previous trials to predict this trial.  

1. How would a voter's likelihood of support for the candidate change if they had personal contact with the candidate?

Answer:

Inferential because we are not predicting anything numeric. We use a change in a single variable to see if there is a difference in outcome. 

<br>

## Github Repo Link

[https://github.com/STAT301III/l01-review-goldylocks24](https://github.com/STAT301III/l01-review-goldylocks24){target="_blank"}
